Add capacitor plugin docs
RevenueCat/revenuecat-docs pull request #333
Opened 2023-08-31 11:16 UTC by tonidero

## Motivation / Description

This PR adds the new docs with code samples for the capacitor plugin

2023-08-31 11:33 UTC, tonidero commented on code_blocks/👥 Customers/user-ids_15.js
> +Purchases.configureWith({ apiKey: <public_sdk_key>, appUserID: <my_app_user_id> });
I took the chance to update some code from cordova that was outdated

2023-09-08 14:21 UTC, aboedo commented on code_blocks/👥 Customers/customer-info_add_listener_capacitor.ts
> +	// handle any changes to customerInfo
indentation here seems a bit too much, right?

2023-09-08 14:21 UTC, aboedo commented on code_blocks/👥 Customers/user-ids_23.js
> +Purchases.configureWith({ apiKey: <public_sdk_key> });
why is this the only one that does `configureWith` and not `configure`?

2023-09-08 14:21 UTC, aboedo commented on code_blocks/👥 Customers/user-ids_configure_and_login.ts
> +// Later log in provided user Id
```suggestion
// Later log in providing user Id
```

2023-09-08 14:21 UTC, aboedo commented on code_blocks/🚀 Getting Started/configuring-sdk_8.ts
> +const onDeviceReady = async () => {
feels like we should suffix these with the platform to make it easier to understand where they'll go? We have 3 typescript SDKs

2023-09-08 14:21 UTC, aboedo commented on code_blocks/🚀 Getting Started/displaying-products_choose_offering_capacitor.ts
> +try {
[unrelated to this PR]
kinda hard to review some of these snippets on their own without the rest of the context tbh, and going into the source md file and seeing a pointer to a snippet is also less than convenient. Ideally we'd review directly based on the rendered docs. @vegaro thoughts?

2023-09-08 14:21 UTC, aboedo commented on code_blocks/🚀 Getting Started/installation/ionic_capacitor.txt
> +npm install @revenuecat/purchases-capacitor
yessss

2023-09-08 14:21 UTC, aboedo commented on code_blocks/🚀 Getting Started/installation/ionic_react_capacitor.ts
> +        <IonButton onClick={openScanner}>Scan barcode</IonButton>
is this Ionic's version of a hello world? Wonder if we should make it revenueCat themed or at least a regular hello world

2023-09-08 14:21 UTC, aboedo commented on code_blocks/🚀 Getting Started/making-purchases_capacitor.ts
> +  if (error.code === PURCHASES_ERROR_CODE.PURCHASE_CANCELLED_ERROR) {
could you elaborate? What would you add?

2023-09-08 14:21 UTC, aboedo commented on code_blocks/🚀 Getting Started/making-purchases_capacitor.ts
> +  const purchaseResult = await Purchases.purchaseStoreProduct({
what does this mean? what happens if I'm on iOS?

2023-09-08 14:21 UTC, aboedo commented on code_blocks/🚀 Getting Started/making-purchases_capacitor.ts
> +  const purchaseResult = await Purchases.purchaseStoreProduct({
I think this message is only needed when you just try to purchase product by id directly rather than storeProduct?

2023-09-08 14:21 UTC, aboedo commented on docs_source/👥 Customers/customer-info.md
> +    "name": "Cordova/Capacitor",
If we're looking to promote Capacitor and deprecate Cordova, I'd do `Capacitor/Cordova` instead

2023-09-08 14:21 UTC, aboedo commented on code_blocks/🚀 Getting Started/configuring-sdk_8.ts
> +const onDeviceReady = async () => {
feels like something we could set up in danger based on the directory or something? cc @vegaro for thoughts

2023-09-08 14:30 UTC, tonidero commented on code_blocks/🚀 Getting Started/making-purchases_capacitor.ts
> +  if (error.code === PURCHASES_ERROR_CODE.PURCHASE_CANCELLED_ERROR) {
I was thinking of a property, like we do in the natives, that explicitely indicates whether the purchase was cancelled, instead of having to check the error code... That has its own problems since that data then lives in 2 places, that property and the error code, but might make it easier. I think this is ok for now though

2023-09-08 15:27 UTC, tonidero commented on code_blocks/👥 Customers/customer-info_add_listener_capacitor.ts
> +	// handle any changes to customerInfo
It is one tab... but `ts` usually uses 2 spaces, so I will change it.

2023-09-08 15:27 UTC, tonidero commented on code_blocks/👥 Customers/user-ids_23.js
> +Purchases.configureWith({ apiKey: <public_sdk_key> });
This is `Cordova` that uses `configureWith`... For `Capacitor`, I approached more RN's API, which uses `configure`

2023-09-08 15:27 UTC, tonidero commented on code_blocks/🚀 Getting Started/configuring-sdk_8.ts
> +const onDeviceReady = async () => {
Ahh yes you're right. I did that for the Capacitor plugin, but on a second round and forgot this one. Updating

2023-09-08 15:27 UTC, tonidero commented on code_blocks/🚀 Getting Started/configuring-sdk_8.ts
> +const onDeviceReady = async () => {
And might be good to separate somehow... Since it's indeed tricky to read right now

2023-09-08 15:27 UTC, tonidero commented on code_blocks/🚀 Getting Started/displaying-products_choose_offering_capacitor.ts
> +try {
We'd need to check in the rendered docs I guess? But yeah, it can be annoying...

2023-09-08 15:27 UTC, tonidero commented on code_blocks/🚀 Getting Started/installation/ionic_react_capacitor.ts
> +        <IonButton onClick={openScanner}>Scan barcode</IonButton>
I copied the example we had for Cordova and just updated the code that uses our SDK and imports. But yeah, I will change it to something closer to home

2023-09-08 15:27 UTC, tonidero commented on code_blocks/🚀 Getting Started/making-purchases_capacitor.ts
> +  const purchaseResult = await Purchases.purchaseStoreProduct({
Hmm right, this is copied from the cordova version but didn't notice that difference. Good catch!

2023-09-11 14:42 UTC, aboedo requested changes
looking great! But I found a couple of outdated references we should fix before shipping

2023-09-11 14:42 UTC, aboedo commented on code_blocks/🚀 Getting Started/displaying-products_get_offerings_product_capacitor.ts
> +			// Get the price and introductory period from the PurchasesProduct
indentation is broken in this line

2023-09-11 14:42 UTC, aboedo commented on code_blocks/🚀 Getting Started/installation/ionic_react_capacitor.ts
> +        <IonButton onClick={purchasePackage}>Buy subscription</IonButton>
```suggestion
        <IonButton onClick={purchasePackage}>Subscribe now</IonButton>
```

2023-09-11 14:42 UTC, aboedo commented on code_blocks/🚀 Getting Started/installation/ionic_react_cordova.ts
> +        <IonButton onClick={purchasePackage}>Buy subscription</IonButton>
```suggestion
        <IonButton onClick={purchasePackage}>Subscribe now</IonButton>
```

2023-09-11 14:42 UTC, aboedo commented on docs_source/🚀 Getting Started/installation/ionic.md
> +    "file": "code_blocks/🚀 Getting Started/installation/ionic_capacitor.txt"
we need to update the copy at the start of this file, that reads: 

> We currently only offer an official Cordova plugin. Install the plugin depending on your framework: 

this is no longer true, we should mention that we support Capacitor and Cordova but we recommend Capacitor for Ionic apps

2023-09-11 14:42 UTC, aboedo commented on code_blocks/🚀 Getting Started/installation/ionic_capacitor.txt
>  // Install Cordova plugin
this still says "Install Cordova plugin" 😅

2023-09-11 14:49 UTC, tonidero commented on code_blocks/🚀 Getting Started/displaying-products_get_offerings_product_capacitor.ts
> +			// Get the price and introductory period from the PurchasesProduct
Wow... it looked fine locally, but it's using tabs instead of spaces. Good catch!

2023-09-11 14:56 UTC, tonidero commented on docs_source/🚀 Getting Started/installation/ionic.md
> +    "file": "code_blocks/🚀 Getting Started/installation/ionic_capacitor.txt"
Updated, lmk what you think!

2023-09-11 15:17 UTC, vegaro commented on code_blocks/🚀 Getting Started/displaying-products_choose_offering_capacitor.ts
> +try {
Interesting. This is really good feedback. I'll think about that. It would mean changing the current flow and rendering in the PRs instead of in the automatic PR

2023-09-11 16:43 UTC, aboedo approved these changes

2023-09-11 16:43 UTC, aboedo commented on docs_source/🚀 Getting Started/installation/ionic.md
> +We currently offer official Capacitor and Cordova plugins. We recommend using the Capacitor plugin when possible. Install the plugin depending on your framework:
I think at this point we can remove the "currently" here, since it was meant to indicate some intermediate state and with the Capacitor plugin we're at a stable state from now on. 
```suggestion
We offer official plugins for both Capacitor and Cordova. We recommend using the Capacitor plugin when possible. Install the plugin depending on your framework:
```

2023-09-12 08:43 UTC, merged